ALTER TABLE "Institution" RENAME TO "MsInstitution";
ALTER TABLE "User" RENAME TO "MsUser";
ALTER TABLE "Session" RENAME TO "TrSession";
ALTER TABLE "Account" RENAME TO "MsAccount";
ALTER TABLE "Verification" RENAME TO "TrVerification";
ALTER TABLE "Participant" RENAME TO "MsParticipant";
ALTER TABLE "GameRuleVersion" RENAME TO "MsGameRuleVersion";
ALTER TABLE "GamePreparation" RENAME TO "TrGamePreparation";
ALTER TABLE "SessionCreationRequest" RENAME TO "TrSessionCreationRequest";
ALTER TABLE "GameSession" RENAME TO "TrGameSession";
ALTER TABLE "GameResult" RENAME TO "TrGameResult";
ALTER TABLE "GameTrial" RENAME TO "TrGameTrial";
ALTER TABLE "AiSessionSummary" RENAME TO "TrAiSessionSummary";
ALTER TABLE "AuditLog" RENAME TO "TrAuditLog";
ALTER TABLE "OutboxEvent" RENAME TO "TrOutboxEvent";

ALTER TABLE "MsInstitution" RENAME CONSTRAINT "Institution_pkey" TO "MsInstitution_pkey";
ALTER TABLE "MsUser" RENAME CONSTRAINT "User_pkey" TO "MsUser_pkey";
ALTER TABLE "TrSession" RENAME CONSTRAINT "Session_pkey" TO "TrSession_pkey";
ALTER TABLE "MsAccount" RENAME CONSTRAINT "Account_pkey" TO "MsAccount_pkey";
ALTER TABLE "TrVerification" RENAME CONSTRAINT "Verification_pkey" TO "TrVerification_pkey";
ALTER TABLE "MsParticipant" RENAME CONSTRAINT "Participant_pkey" TO "MsParticipant_pkey";
ALTER TABLE "MsGameRuleVersion" RENAME CONSTRAINT "GameRuleVersion_pkey" TO "MsGameRuleVersion_pkey";
ALTER TABLE "TrGamePreparation" RENAME CONSTRAINT "GamePreparation_pkey" TO "TrGamePreparation_pkey";
ALTER TABLE "TrSessionCreationRequest" RENAME CONSTRAINT "SessionCreationRequest_pkey" TO "TrSessionCreationRequest_pkey";
ALTER TABLE "TrGameSession" RENAME CONSTRAINT "GameSession_pkey" TO "TrGameSession_pkey";
ALTER TABLE "TrGameResult" RENAME CONSTRAINT "GameResult_pkey" TO "TrGameResult_pkey";
ALTER TABLE "TrGameTrial" RENAME CONSTRAINT "GameTrial_pkey" TO "TrGameTrial_pkey";
ALTER TABLE "TrAiSessionSummary" RENAME CONSTRAINT "AiSessionSummary_pkey" TO "TrAiSessionSummary_pkey";
ALTER TABLE "TrAuditLog" RENAME CONSTRAINT "AuditLog_pkey" TO "TrAuditLog_pkey";
ALTER TABLE "TrOutboxEvent" RENAME CONSTRAINT "OutboxEvent_pkey" TO "TrOutboxEvent_pkey";

ALTER TABLE "MsUser" RENAME CONSTRAINT "User_institutionId_fkey" TO "MsUser_institutionId_fkey";
ALTER TABLE "TrSession" RENAME CONSTRAINT "Session_userId_fkey" TO "TrSession_userId_fkey";
ALTER TABLE "MsAccount" RENAME CONSTRAINT "Account_userId_fkey" TO "MsAccount_userId_fkey";
ALTER TABLE "MsParticipant" RENAME CONSTRAINT "Participant_institutionId_fkey" TO "MsParticipant_institutionId_fkey";
ALTER TABLE "MsGameRuleVersion" RENAME CONSTRAINT "GameRuleVersion_institutionId_fkey" TO "MsGameRuleVersion_institutionId_fkey";
ALTER TABLE "TrGamePreparation" RENAME CONSTRAINT "GamePreparation_institutionId_fkey" TO "TrGamePreparation_institutionId_fkey";
ALTER TABLE "TrGamePreparation" RENAME CONSTRAINT "GamePreparation_participantId_fkey" TO "TrGamePreparation_participantId_fkey";
ALTER TABLE "TrGamePreparation" RENAME CONSTRAINT "GamePreparation_ruleVersionId_fkey" TO "TrGamePreparation_ruleVersionId_fkey";
ALTER TABLE "TrGamePreparation" RENAME CONSTRAINT "GamePreparation_tenant_participant_fkey" TO "TrGamePreparation_tenant_participant_fkey";
ALTER TABLE "TrGamePreparation" RENAME CONSTRAINT "GamePreparation_mode_rule_fkey" TO "TrGamePreparation_mode_rule_fkey";
ALTER TABLE "TrSessionCreationRequest" RENAME CONSTRAINT "SessionCreationRequest_sessionId_fkey" TO "TrSessionCreationRequest_sessionId_fkey";
ALTER TABLE "TrGameSession" RENAME CONSTRAINT "GameSession_institutionId_fkey" TO "TrGameSession_institutionId_fkey";
ALTER TABLE "TrGameSession" RENAME CONSTRAINT "GameSession_participantId_fkey" TO "TrGameSession_participantId_fkey";
ALTER TABLE "TrGameSession" RENAME CONSTRAINT "GameSession_preparationId_fkey" TO "TrGameSession_preparationId_fkey";
ALTER TABLE "TrGameSession" RENAME CONSTRAINT "GameSession_ruleVersionId_fkey" TO "TrGameSession_ruleVersionId_fkey";
ALTER TABLE "TrGameSession" RENAME CONSTRAINT "GameSession_tenant_participant_fkey" TO "TrGameSession_tenant_participant_fkey";
ALTER TABLE "TrGameSession" RENAME CONSTRAINT "GameSession_preparation_source_fkey" TO "TrGameSession_preparation_source_fkey";
ALTER TABLE "TrGameSession" RENAME CONSTRAINT "GameSession_mode_rule_fkey" TO "TrGameSession_mode_rule_fkey";
ALTER TABLE "TrGameResult" RENAME CONSTRAINT "GameResult_sessionId_fkey" TO "TrGameResult_sessionId_fkey";
ALTER TABLE "TrGameResult" RENAME CONSTRAINT "GameResult_institutionId_fkey" TO "TrGameResult_institutionId_fkey";
ALTER TABLE "TrGameResult" RENAME CONSTRAINT "GameResult_participantId_fkey" TO "TrGameResult_participantId_fkey";
ALTER TABLE "TrGameResult" RENAME CONSTRAINT "GameResult_ruleVersionId_fkey" TO "TrGameResult_ruleVersionId_fkey";
ALTER TABLE "TrGameResult" RENAME CONSTRAINT "GameResult_session_source_fkey" TO "TrGameResult_session_source_fkey";
ALTER TABLE "TrGameResult" RENAME CONSTRAINT "GameResult_tenant_participant_fkey" TO "TrGameResult_tenant_participant_fkey";
ALTER TABLE "TrGameResult" RENAME CONSTRAINT "GameResult_mode_rule_fkey" TO "TrGameResult_mode_rule_fkey";
ALTER TABLE "TrGameTrial" RENAME CONSTRAINT "GameTrial_sessionId_fkey" TO "TrGameTrial_sessionId_fkey";
ALTER TABLE "TrAiSessionSummary" RENAME CONSTRAINT "AiSessionSummary_sessionId_fkey" TO "TrAiSessionSummary_sessionId_fkey";
ALTER TABLE "TrAuditLog" RENAME CONSTRAINT "AuditLog_institutionId_fkey" TO "TrAuditLog_institutionId_fkey";

ALTER INDEX "Institution_status_idx" RENAME TO "MsInstitution_status_idx";
ALTER INDEX "User_email_key" RENAME TO "MsUser_email_key";
ALTER INDEX "User_institutionId_key" RENAME TO "MsUser_institutionId_key";
ALTER INDEX "Session_token_key" RENAME TO "TrSession_token_key";
ALTER INDEX "Session_userId_idx" RENAME TO "TrSession_userId_idx";
ALTER INDEX "Account_userId_idx" RENAME TO "MsAccount_userId_idx";
ALTER INDEX "Account_providerId_accountId_key" RENAME TO "MsAccount_providerId_accountId_key";
ALTER INDEX "Verification_identifier_idx" RENAME TO "TrVerification_identifier_idx";
ALTER INDEX "Participant_participantId_key" RENAME TO "MsParticipant_participantId_key";
ALTER INDEX "Participant_institutionId_status_idx" RENAME TO "MsParticipant_institutionId_status_idx";
ALTER INDEX "Participant_institutionId_participantReference_key" RENAME TO "MsParticipant_institutionId_participantReference_key";
ALTER INDEX "Participant_tenant_identity_key" RENAME TO "MsParticipant_tenant_identity_key";
ALTER INDEX "GameRuleVersion_institutionId_mode_isActive_idx" RENAME TO "MsGameRuleVersion_institutionId_mode_isActive_idx";
ALTER INDEX "GameRuleVersion_institutionId_mode_version_key" RENAME TO "MsGameRuleVersion_institutionId_mode_version_key";
ALTER INDEX "GameRuleVersion_mode_key" RENAME TO "MsGameRuleVersion_mode_key";
ALTER INDEX "GamePreparation_preparationId_key" RENAME TO "TrGamePreparation_preparationId_key";
ALTER INDEX "GamePreparation_setupId_key" RENAME TO "TrGamePreparation_setupId_key";
ALTER INDEX "GamePreparation_institutionId_ownerSessionId_state_idx" RENAME TO "TrGamePreparation_institutionId_ownerSessionId_state_idx";
ALTER INDEX "GamePreparation_expiresAt_state_idx" RENAME TO "TrGamePreparation_expiresAt_state_idx";
ALTER INDEX "GamePreparation_session_source_key" RENAME TO "TrGamePreparation_session_source_key";
ALTER INDEX "SessionCreationRequest_sessionId_key" RENAME TO "TrSessionCreationRequest_sessionId_key";
ALTER INDEX "SessionCreationRequest_expiresAt_idx" RENAME TO "TrSessionCreationRequest_expiresAt_idx";
ALTER INDEX "SessionCreationRequest_ownerSessionId_idempotencyKey_key" RENAME TO "TrSessionCreationRequest_ownerSessionId_idempotencyKey_key";
ALTER INDEX "GameSession_activationId_key" RENAME TO "TrGameSession_activationId_key";
ALTER INDEX "GameSession_institutionId_participantId_completedAt_idx" RENAME TO "TrGameSession_institutionId_participantId_completedAt_idx";
ALTER INDEX "GameSession_status_finalizationRecoveryExpiresAt_idx" RENAME TO "TrGameSession_status_finalizationRecoveryExpiresAt_idx";
ALTER INDEX "GameSession_ownerSessionId_status_idx" RENAME TO "TrGameSession_ownerSessionId_status_idx";
ALTER INDEX "GameSession_result_source_key" RENAME TO "TrGameSession_result_source_key";
ALTER INDEX "GameResult_sessionId_key" RENAME TO "TrGameResult_sessionId_key";
ALTER INDEX "GameResult_institutionId_participantId_mode_gameRuleVersion_idx" RENAME TO "TrGameResult_institutionId_participantId_mode_gameRuleVersi_idx";
ALTER INDEX "GameTrial_sessionId_idx" RENAME TO "TrGameTrial_sessionId_idx";
ALTER INDEX "GameTrial_sessionId_trialIndex_attemptIndex_key" RENAME TO "TrGameTrial_sessionId_trialIndex_attemptIndex_key";
ALTER INDEX "AiSessionSummary_sessionId_key" RENAME TO "TrAiSessionSummary_sessionId_key";
ALTER INDEX "AiSessionSummary_status_availableAt_leaseExpiresAt_idx" RENAME TO "TrAiSessionSummary_status_availableAt_leaseExpiresAt_idx";
ALTER INDEX "AuditLog_institutionId_createdAt_idx" RENAME TO "TrAuditLog_institutionId_createdAt_idx";
ALTER INDEX "AuditLog_action_createdAt_idx" RENAME TO "TrAuditLog_action_createdAt_idx";
ALTER INDEX "OutboxEvent_eventKey_key" RENAME TO "TrOutboxEvent_eventKey_key";
ALTER INDEX "OutboxEvent_status_availableAt_leaseExpiresAt_idx" RENAME TO "TrOutboxEvent_status_availableAt_leaseExpiresAt_idx";
